- pkg:nuget/AppOS.Monitoring.Prometheus@1.0.4
- pkg:nuget/AppOS.Monitoring.Prometheus@1.0.5
- pkg:nuget/AppOS.Monitoring.Prometheus@1.0.6
- pkg:nuget/AppOS.Monitoring.Prometheus@1.0.7
- pkg:nuget/AppOS.Monitoring.Prometheus@1.1.0
- pkg:nuget/AppOS.Monitoring.Prometheus@2.0.0
- pkg:nuget/AppOS.Monitoring.Prometheus@3.0.2
- pkg:nuget/AppOS.Monitoring.Prometheus@3.4.1
